name: app_movil_channel_iptv
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  connectivity: ^3.0.6
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  #flutter_secure_storage: ^8.0.0
  flutter_vlc_player: ^7.4.1
  http: ^1.1.0
  intl: ^0.19.0
  lottie: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/streamImg.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/img/streamImg.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/img/streamImg.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/img/streamImg.png"

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/animation/